/**
 * Tailwind config for building the standalone stylesheet shipped with the
 * package (`dist/styles.css`). Consumers who do NOT use Tailwind can simply
 * import that file. Consumers who DO use Tailwind can instead add this package
 * to their own `content` globs (and mirror the `safelist` below) so the utility
 * classes are generated by their build.
 *
 * Preflight is disabled so importing the stylesheet never resets the host app's
 * base styles — every element the component renders carries explicit classes.
 */

const colors = [
  "slate", "gray", "zinc", "neutral", "stone",
  "red", "orange", "amber", "yellow", "lime", "green", "emerald", "teal",
  "cyan", "sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose",
]
const shades = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"]

const colorGroup = colors.join("|")
const shadeGroup = shades.join("|")

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  corePlugins: {
    preflight: false,
  },
  safelist: [
    // Category colors are supplied at runtime by consumer config, so the
    // relevant background/ring/text utilities must be generated unconditionally.
    { pattern: new RegExp(`^bg-(${colorGroup})-(${shadeGroup})$`) },
    { pattern: new RegExp(`^text-(${colorGroup})-(${shadeGroup})$`) },
    { pattern: new RegExp(`^ring-(${colorGroup})-(${shadeGroup})$`) },
    { pattern: new RegExp(`^border-(${colorGroup})-(${shadeGroup})$`) },
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
